language: node_js
node_js:
  - "lts/carbon"
before_script:
  - export TZ=America/New_York
install:
    - npm install
cache:
  directories:
    - node_modules
    - $HOME/.mongodb-binaries
script:
  - npm test
  - npm run lint
